import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/header";
import { Providers } from "@/redux/provider";
import { Setup } from "@/components/utility";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JWT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {" "}
        <Providers>
          <Setup />
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
